"""Reason codes Portfolio Manager can produce -- additive, distinct from `risk_manager`/`risk_manager_live`
vocabulary (those gate at the single-trade level; these gate at the aggregate-book level, a genuinely
different authority, so no code here collides with or duplicates a Risk Manager code)."""

from __future__ import annotations

PORTFOLIO_TOTAL_EXPOSURE = "PORTFOLIO_TOTAL_EXPOSURE"
PORTFOLIO_RESERVED_CAPITAL = "PORTFOLIO_RESERVED_CAPITAL"
PORTFOLIO_DIRECTION_EXPOSURE = "PORTFOLIO_DIRECTION_EXPOSURE"
PORTFOLIO_STRATEGY_EXPOSURE = "PORTFOLIO_STRATEGY_EXPOSURE"
PORTFOLIO_SESSION_EXPOSURE = "PORTFOLIO_SESSION_EXPOSURE"
PORTFOLIO_ASSET_CLASS_EXPOSURE = "PORTFOLIO_ASSET_CLASS_EXPOSURE"
PORTFOLIO_LONG_SHORT_CONFLICT = "PORTFOLIO_LONG_SHORT_CONFLICT"
PORTFOLIO_HEAT = "PORTFOLIO_HEAT"
PORTFOLIO_DAILY_TRADE_COUNT = "PORTFOLIO_DAILY_TRADE_COUNT"
PORTFOLIO_DAILY_HEAT = "PORTFOLIO_DAILY_HEAT"
PORTFOLIO_STATE_UNAVAILABLE = "PORTFOLIO_STATE_UNAVAILABLE"
