"""Canonical NO_TRADE reason codes (AI Trader New Brain Architecture mandate, section 22). Every
`NO_TRADE` outcome anywhere in `strategy_platform` carries exactly one of these -- never a silent
decision, never a free-text reason invented ad hoc at the call site."""

from __future__ import annotations

NO_VALIDATED_STRATEGY = "NO_VALIDATED_STRATEGY"
NO_ELIGIBLE_STRATEGY = "NO_ELIGIBLE_STRATEGY"
NO_STRATEGY_SIGNAL = "NO_STRATEGY_SIGNAL"
EV_BELOW_THRESHOLD = "EV_BELOW_THRESHOLD"
RISK_REJECTED = "RISK_REJECTED"
DATA_NOT_READY = "DATA_NOT_READY"
MARKET_STATE_INVALID = "MARKET_STATE_INVALID"
BROKER_DISABLED = "BROKER_DISABLED"
CONFLICT_POLICY_BLOCK = "CONFLICT_POLICY_BLOCK"
STALE_INPUT = "STALE_INPUT"
INTEGRITY_FAILURE = "INTEGRITY_FAILURE"

# ── added by VE-AI-TRADER-GENERIC-EV-AUTHORITY-001 (real_ev_engine.py) -- additive, the 11 codes above are
# unchanged. RealEVDecisionEngine's admission/schema/geometry gate has more distinct failure modes than the
# Mock engine ever needed (it only ever produces EV_BELOW_THRESHOLD); each gets its own named, auditable code
# rather than overloading one of the 11 above or inventing an unregistered free-text string. ──
UNKNOWN_STRATEGY = "UNKNOWN_STRATEGY"
STRATEGY_DISABLED = "STRATEGY_DISABLED"
STRATEGY_POLICY_MISMATCH = "STRATEGY_POLICY_MISMATCH"
MARKET_STATE_MISMATCH = "MARKET_STATE_MISMATCH"
INCOMPATIBLE_N1_CONTRACT = "INCOMPATIBLE_N1_CONTRACT"
SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
MISSING_PROBABILITY_INPUTS = "MISSING_PROBABILITY_INPUTS"
NEGATIVE_EXPECTED_VALUE = "NEGATIVE_EXPECTED_VALUE"
INFEASIBLE_GEOMETRY = "INFEASIBLE_GEOMETRY"
REAL_EV_VALIDATED_EDGE = "REAL_EV_VALIDATED_EDGE"
REAL_EV_AUTHORITY_UNAVAILABLE = "REAL_EV_AUTHORITY_UNAVAILABLE"

# ── added by VE-S5-REAL-EV-RUNTIME-PACKAGING-001 -- additive, the 21 codes above are unchanged. A
# validated-evidence package (e.g. S5_REAL_EV_EVIDENCE_V1) carries its OWN claimed strategy/cost identity
# inside `expected_edge`; RealEVDecisionEngine cross-checks those claims against the catalog entry / cost
# model it already has, generically, for any strategy that attaches such a package -- these two codes name
# that specific class of failure distinctly from a merely-missing or schema-malformed edge. ──
EVIDENCE_IDENTITY_MISMATCH = "EVIDENCE_IDENTITY_MISMATCH"
EVIDENCE_COST_IDENTITY_MISMATCH = "EVIDENCE_COST_IDENTITY_MISMATCH"

ALL_REASON_CODES = frozenset({
    NO_VALIDATED_STRATEGY, NO_ELIGIBLE_STRATEGY, NO_STRATEGY_SIGNAL, EV_BELOW_THRESHOLD, RISK_REJECTED,
    DATA_NOT_READY, MARKET_STATE_INVALID, BROKER_DISABLED, CONFLICT_POLICY_BLOCK, STALE_INPUT,
    INTEGRITY_FAILURE,
    UNKNOWN_STRATEGY, STRATEGY_DISABLED, STRATEGY_POLICY_MISMATCH, MARKET_STATE_MISMATCH,
    INCOMPATIBLE_N1_CONTRACT, SCHEMA_VALIDATION_FAILED, MISSING_PROBABILITY_INPUTS, NEGATIVE_EXPECTED_VALUE,
    INFEASIBLE_GEOMETRY, REAL_EV_VALIDATED_EDGE, REAL_EV_AUTHORITY_UNAVAILABLE,
    EVIDENCE_IDENTITY_MISMATCH, EVIDENCE_COST_IDENTITY_MISMATCH,
})
