"""Canonical NO_TRADE reason codes (AI Trader New Brain Architecture mandate, section 22). Every
`NO_TRADE` outcome anywhere in `strategy_platform` carries exactly one of these -- never a silent
decision, never a free-text reason invented ad hoc at the call site."""

from __future__ import annotations

NO_VALIDATED_STRATEGY = "NO_VALIDATED_STRATEGY"
NO_ELIGIBLE_STRATEGY = "NO_ELIGIBLE_STRATEGY"
NO_STRATEGY_SIGNAL = "NO_STRATEGY_SIGNAL"
EV_BELOW_THRESHOLD = "EV_BELOW_THRESHOLD"
RISK_REJECTED = "RISK_REJECTED"
DATA_NOT_READY = "DATA_NOT_READY"
MARKET_STATE_INVALID = "MARKET_STATE_INVALID"
BROKER_DISABLED = "BROKER_DISABLED"
CONFLICT_POLICY_BLOCK = "CONFLICT_POLICY_BLOCK"
STALE_INPUT = "STALE_INPUT"
INTEGRITY_FAILURE = "INTEGRITY_FAILURE"

ALL_REASON_CODES = frozenset({
    NO_VALIDATED_STRATEGY, NO_ELIGIBLE_STRATEGY, NO_STRATEGY_SIGNAL, EV_BELOW_THRESHOLD, RISK_REJECTED,
    DATA_NOT_READY, MARKET_STATE_INVALID, BROKER_DISABLED, CONFLICT_POLICY_BLOCK, STALE_INPUT,
    INTEGRITY_FAILURE,
})
