"""Reason codes Confidence Engine can produce -- additive, distinct from any Risk/Portfolio Manager
vocabulary (this layer never decides risk)."""

from __future__ import annotations

MARKET_INTELLIGENCE_UNAVAILABLE = "MARKET_INTELLIGENCE_UNAVAILABLE"
DATA_QUALITY_NOT_OK = "DATA_QUALITY_NOT_OK"
DATA_STALE = "DATA_STALE"
RECOGNITION_PATTERN_UNAUTHORIZED = "RECOGNITION_PATTERN_UNAUTHORIZED"
GRADE_BELOW_ELIGIBLE_THRESHOLD = "GRADE_BELOW_ELIGIBLE_THRESHOLD"
ASSESSMENT_FAILED = "ASSESSMENT_FAILED"
