"""Reason codes MT5 Demo Execution can produce -- additive, distinct from every other layer's own
vocabulary."""

from __future__ import annotations

TRADING_DISABLED_AT_TERMINAL = "TRADING_DISABLED_AT_TERMINAL"
NON_DEMO_ACCOUNT_REFUSED = "NON_DEMO_ACCOUNT_REFUSED"
UNEXPECTED_SERVER = "UNEXPECTED_SERVER"
VOLUME_EXCEEDS_CONFIGURED_MAXIMUM = "VOLUME_EXCEEDS_CONFIGURED_MAXIMUM"
ORDER_CHECK_FAILED = "ORDER_CHECK_FAILED"
ORDER_SEND_FAILED = "ORDER_SEND_FAILED"
NOT_CONNECTED = "NOT_CONNECTED"
SAFETY_GUARDS_FAILED = "SAFETY_GUARDS_FAILED"
DRY_RUN_DID_NOT_PASS = "DRY_RUN_DID_NOT_PASS"
MARKET_CLOSED = "MARKET_CLOSED"
LEGACY_TRADING_AUTHORITY_QUARANTINED = "LEGACY_TRADING_AUTHORITY_QUARANTINED"
