"""Reason codes the Execution Orchestrator's own coordination logic can produce -- additive, distinct
from every downstream engine's own vocabulary (which is reused verbatim, unmodified, when a downstream
engine denies)."""

from __future__ import annotations

EMERGENCY_STOP_ACTIVE = "EMERGENCY_STOP_ACTIVE"
LIVE_TRADING_NOT_AUTHORIZED = "LIVE_TRADING_NOT_AUTHORIZED"
NON_DEMO_ACCOUNT_REFUSED = "NON_DEMO_ACCOUNT_REFUSED"
STALE_CANDIDATE = "STALE_CANDIDATE"
CONTEXT_BUILD_FAILED = "CONTEXT_BUILD_FAILED"
CONFIDENCE_ASSESSMENT_FAILED = "CONFIDENCE_ASSESSMENT_FAILED"
NOT_ELIGIBLE_FOR_RISK_EVALUATION = "NOT_ELIGIBLE_FOR_RISK_EVALUATION"
RISK_EVALUATION_FAILED = "RISK_EVALUATION_FAILED"
RISK_DENIED = "RISK_DENIED"
PORTFOLIO_EVALUATION_FAILED = "PORTFOLIO_EVALUATION_FAILED"
PORTFOLIO_DENIED = "PORTFOLIO_DENIED"
ORDER_MANAGER_FAILED = "ORDER_MANAGER_FAILED"
