"""Strategy Manager v1 — the AI Trader's second module (Phase 6.2).

Public API surface (``STRATEGY_MANAGER_API.md``). Only these names are exported; internal modules
(``loader``, ``compatibility``, ``lifecycle``, ``registry``, ``aggregator``, ``health``,
``required_context``, ``schema_validation``, ``registry_schema_validation``) are implementation
details and may change without notice. Per the separation law
(``STRATEGY_MANAGER_ARCHITECTURE.md`` §1/§7), nothing in this package reads Research Lab artifacts
(``code/``, ``results/``, ``knowledge/experiments/``, ``knowledge/ontology/``) — a strategy is known
ONLY through its Contract (``knowledge/strategies/*/strategy.json``) validated against the frozen
Strategy Interface v1 (``knowledge/interface/strategy_contract.v1.schema.json``).
"""

from ai_trader.strategy_manager.config import ManagerConfig, SupportedVersions
from ai_trader.strategy_manager.contract import (
    Confidence,
    ConfidenceLevel,
    Contract,
    ContractHealth,
    ContractStatus,
    Cooldown,
    CooldownScope,
    Evidence,
    Execution,
    HoldoutStatus,
    Identity,
    LongShort,
    MarketRegimeSpec,
    MatchedNullScope,
    MatchedNullStatus,
    Maturity,
    Metrics,
    Provenance,
    Regime,
    RequiredDataSpec,
    RiskModel,
    RuleSpec,
    Semantics,
)
from ai_trader.strategy_manager.exceptions import (
    IllegalTransitionError,
    ManagerNotConfiguredError,
    SchemaLoadError,
    StrategyApiNotImplementedError,
    StrategyManagerError,
    UnknownStrategyError,
)
from ai_trader.strategy_manager.handle import StrategyHandle, StrategyRuntimeHandle
from ai_trader.strategy_manager.manager import MarketScannerLike, StrategyManager
from ai_trader.strategy_manager.types import (
    ACTIVATABLE_LIFECYCLES,
    AggregatedContext,
    CompatibilityResult,
    ContractRef,
    Health,
    Lifecycle,
    LifecycleResult,
    LoadFailure,
    LoadReport,
    ManagerHealth,
    ManagerOverallHealth,
    NotFound,
    RegistryEntry,
    RequiredContext,
    Statistics,
    StrategyView,
    ValidationReport,
    VersionInfo,
)

__all__ = [
    "StrategyManager",
    "MarketScannerLike",
    "ManagerConfig",
    "SupportedVersions",
    "Contract",
    "Identity",
    "ContractStatus",
    "Maturity",
    "ContractHealth",
    "ConfidenceLevel",
    "Confidence",
    "MarketRegimeSpec",
    "RequiredDataSpec",
    "Semantics",
    "RuleSpec",
    "RiskModel",
    "Cooldown",
    "CooldownScope",
    "LongShort",
    "Execution",
    "Metrics",
    "MatchedNullScope",
    "MatchedNullStatus",
    "Evidence",
    "HoldoutStatus",
    "Provenance",
    "Regime",
    "StrategyHandle",
    "StrategyRuntimeHandle",
    "ACTIVATABLE_LIFECYCLES",
    "Lifecycle",
    "Health",
    "ManagerOverallHealth",
    "ContractRef",
    "CompatibilityResult",
    "RequiredContext",
    "AggregatedContext",
    "RegistryEntry",
    "StrategyView",
    "NotFound",
    "LoadFailure",
    "LoadReport",
    "ValidationReport",
    "LifecycleResult",
    "Statistics",
    "ManagerHealth",
    "VersionInfo",
    "StrategyManagerError",
    "ManagerNotConfiguredError",
    "SchemaLoadError",
    "UnknownStrategyError",
    "IllegalTransitionError",
    "StrategyApiNotImplementedError",
]
